
- name: Install httpd package on Node1, 2 & 4
  tags: apache,centos,httpd
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: Start & enable httpd on Redhat
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install apache2 service on Node4 (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Changing e-mail address for default Serveradmin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin yogeshgunasekaran@gmail.com
  when: ansible_distribution == "CentOS"
  register: httpd

- name: Restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: Copy our html file from files/ to Web-Server's defaults
  tags: apache,apache,apache2,httpd
  copy:
    src: our_index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

