
---
- name: Install MySQL serice on Node3
  hosts: group2
  become: yes
  tasks:
    - name: update repository index
      yum:
        update_cache: yes
    
    - name: Install MySQL service
      yum:
        name: mariadb-server  
        state: present
    
    - name: Start & Enable mariadb service
      service:
         name: mariadb
         state: started
         enabled: yes

    - name: Install Python MySQL dependency 
      yum:
         name: MySQL-python
         state: present

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present

    - name: Create database user with name 'admin' 
      mysql_user:
        name: admin
        password: admin123
        priv: '*.*:ALL'
        state: present

