
---
- name: Install httpd service for Node1 and Node2
  hosts: group1
  become: yes
  tasks:
    - name: update repository index
      yum:
        update_cache: yes
    
    - name: Install Apache httpd
      yum:
        name: httpd  
        state: present
    
    - name: Start and Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
      
